### ISSUE TITLE
No sound in the right channel?

### ISSUE THREAD

**Issue by PalMusicFan** [wothke/adplug-2.2.1#2] opened 2018-05-10 03:02 UTC
First of all, thanks for your great work! 

However, it seems there is no sound in the right channel. 

As a test, we have updated the AdPlug core to a (perhaps) later version, and added Surround OPL support. Now the audio output seems to be OK. 

Would you please take a look at our solution? Thanks so much. 
https://github.com/palxex/adplug-emscripten/ 
Demo page: https://palxex.github.io/adplug-emscripten/emscripten/htdocs/index.html
(It seems that Safari also disables Audio auto-play. We solved the problem for Safari, and recently Chrome disabled Audio auto-play too, so our demo is not working on latest Chrome... )

BTW, 49716Hz is the audio output frequency of real OPL2 and OPL3 chips. The resampler is enabled in our demo.

**Comment by wothke** [comment] 2018-05-10 20:19
Hi, thanks for the feedback. 

I already had noticed Google's idiotic "autoplay policy change" and updated all the example screens of "my" various players (see http://www.wothke.ch/tinyrsid/index.php/webaudio-players) so that they can still be used (I just checked-in the respective updated html-sample files in this project - and you might need to use "shift reload" to bypass whatever Chrome still might have cached).

I see that you have used a snapshot of some older version as a base: I had meanwhile updated the emulator to support load-on demand for all those song formats that use more than one file (e.g. separate "instrument" files). This enables the updated version to now play all kinds of songs directly off some remote server (e.g. modland.com).

From what I see you used a different version of adplug with changes in emuopl.*/fmopl.*/surroundopl.* and a different implementation for "rix" files (the rest seems to be pretty much the same). What exactly is the adplug version that you are using? Did you directly mix-in code from MAME or is this from some specific branch? E.g. the version number in the fmopl.cpp suggests that it is a newer version than the one that I had gotten from adplug 2.2.1 (and which still seems to be used in the latest 2.3.1 version). From the comments that I see in the adplug repository they seem to be reluctant to use certain OPL-implementations due to the licensing that comes with these and it seems that they are actually in the midst of switching to a different non-MAME based implementation (personally I try to avoid the shitty GPL license wherever I can...). 

Have you tried what the latest adplug 2.3.1 version sounds like? (i.e. is your fix still required in the latest adplug or has that new version already taken care of the problem?)

**Comment by PalMusicFan** [comment] 2018-05-11 16:30
Thanks for your reply! 
We have just tested your latest version and found where the problem is. Seems that something is wrong with the emuopl core. The right channel sounds well with the temuopl core, and the kemuopl core also has the right channel output. Sorry for the possible misleading!

**Comment by wothke** [comment] 2018-05-11 19:03
My latest version still is based on adplug 2.2.1 and and since this seems to be an issue of the original adplug codebase it would make sense to fix it there (unless it already has been fixed in their latest 2.3.1 version). I will then just update my code to the respective fixed official adplug version (I'd rather avoid maintaining some customized private adplug version - which would unnecessarily complicate merging future adplug releases).
I guess that it should not be much work to merge the older version of my code (the one you had originally been using) with the new adplug 2.3.1 version: The "EMSCRIPTEN" comments in my version will point you to whatever adplug code that I had to touch, and you'd just have to merge those into the new version (and you might need to add any new files to the make-script).

**Comment by PalMusicFan** [comment] 2018-05-12 03:30
Sorry, perhaps I didn't express it clearly in the last post. 
In the test based on your latest version, I tried AdPlug from your latest version (2.2.1), the latest 2.3.1 version from AdPlug official repository, and our forked version. All these three versions has the same problem in the emuopl core. It seems that we had solved the problem by our fork just because we switched the opl core to another one (dosbox opl core, the "main" core we use in our project). So I guess that's just a problem of the emuopl core, not the problem of the version of AdPlug. I think the temuopl core (for example) of adplug 2.2.1 in your version works well.  

BTW, Would you please take a look at something about our forked version of AdPlug? We are the maintainer of the "RIX" unofficial player code. "RIX" format is developed by SOFTSTAR, inc. The forked version of AdPlug is from our SDLPal Project, an unofficial cross platform reimplementation of SOFTSTAR's classic RPG game "Legend of Sword and Fairy".  Yes, it is now specialized for the game and no longer suitable to be merged into the official AdPlug especially after the recent refactoring. 
Much of the new implementation of the RIX player also focus on the SDLPal game itself, except the part of "// This is required for correct attack effect, by louyihua". We found this group of data from the original official EXE. Though we have no idea what exactly they do, the percussion sounds abnormal without them in certain musics. I think we should post a issue for this in AdPlug's repository soon. 

Thanks very much!

**Comment by wothke** [comment] 2018-05-12 08:23
Let me then try to summarize. From what I understand there are three versions of different opl impls involved here: 

1. version 0.37a (see fmopl.c): Old version of the emu used in MAME - which is released under LGPL. This is the version that is used in adplug 2.2.1 (i.e. currently also in my project).
2. version 0.72 (see fmopl.c): A patched/updated version from the MAME project supposedly released under some old MAME license (which restricts commercial redistribution). This version can be found in adplug's github "mame" branch and it seems to be very close to the version that you have been using for your patch (it even seems to be slightly more recent than your version). There seem to be even newer - GPL licensed - versions of this MAME version, which adplug mentions but doesn't use due to their switch to WoodyOPL (see below).
3. WoodyOPL (from DOSBox team): This is the new replacement implementation that adplug currently suggests for use in their 2.3.1 release. It is again licensed using LGPL.

CAUTION: The new adplug 2.3.1 release contains the code for *BOTH* 1 and 3 and depending on your makefile you might still be using the old impl from 1 but not the new WoodyOPL one (see new woodyopl.cpp)!

From what you said you tested all 3 versions and except for your patched version of 2 the problem is present in all of them. Is that correct? (did you really test the WoodyOPL impl as well?)

BTW: I am NOT familiar with the details of OPL emulation and am merely using the respective code as a black-box. Any questions in this area should rather be directed directly at the adplug team - those guys might also be aware of the respective benefits of using one specific impl rather than the other.. (which I am not).

BTW, does the problem that you have identified only affect RIX files or also others? If so, you might want to double check that it's not just a problem of how the RIX player uses the OPL stuff.. 

If it isn't then it is certainly something worth fixing on the OPL emu side. And given the direction that adplug seems to be taking, it should probably be fixed in the WoodyOPL version (there is little point in fixing it in obsolete old impls when those will no longer be used anyway - unless of course WoodyOPL might be such a bad impl than one has to stick to the MAME impl.. ) In any case it would make sense to then open a respective problem ticket in the adplug project so that the issue can be fixed at the source..

**Comment by PalMusicFan** [comment] 2018-05-13 03:11
Yes, the problem affects other formats. 
At this moment, we haven't met this problem in other implementations of AdPlug. Perhaps It is only here that the emuopl core has this problem. 

About the cores: 
The "DOSBox core" we used is not exactly the WoodyOPL. It is a bit complex so let's put it away at this moment. 
Now let's focus on adplug-2.2.1 in your project. 
We know the emuopl core has the problem. But The temuopl core also uses fmopl.c 0.37a, and it works well without the problem. So I don't think there is anything wrong within fmopl.c 0.37a. 

I haven't tested WoodyOPL of adplug-2.3.1 yet. I switched to adplug-2.3.1, modified the make-script, and tried to use WoodyOPL, but I saw the output like this: 
warning: unresolved symbol: _ZN12OPLChipClass10adlib_initEjjj
warning: unresolved symbol: _ZN12OPLChipClass11adlib_writeEjh
warning: unresolved symbol: _ZN12OPLChipClass15adlib_getsampleEPsi
So I had to stop here. 
Actually, recently I always get "unresolved symbol" warnings when I tries to add new files to the project.  
(Test environment: emscripten sdk-1.37.40-64bit, Chrome 66.0.3359.139. )

BTW, Personally I am not a developer (I am a tester of SDLPal Team), and I am not familiar with GitHub issue system yet. I apologize for any inconvenience caused to you (e.g too many edits). 

Thanks very much!

**Comment by wothke** [comment] 2018-05-13 15:09
I updated to adplug 2.3.1 and the use of the WoodyOPL impl. The problem no longer seems to occur in this configuration.

**Comment by PalMusicFan** [comment] 2018-05-15 05:20
Great job! 
It works well on my desktop computers and Android phones. 
I have tested the NukedOPL core as well. This core is amazing! Its main advantage is, it always produces wave data of 49716Hz sample rate (similar as a real OPL3 chip) and it is able to resample the wave data to a standard sample rate with its efficient internal resampler. On a Snapdragon 616 (MSM8939v2) Android 5 phone, it runs smoothly on Mobile Firefox (not smoothly enough on Mobile Chrome here).

**Comment by wothke** [comment] 2018-05-17 11:04
I think this issue can be closed then.

**Closed as completed by wothke** 2018-05-17 11:04 UTC
